name: PHPUnit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test & Upload coverage.xml to Codecov
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Check PHP Version
        run: php -v

      - name: Install Composer Dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run tests via PHPUnit
        env:
          XDEBUG_MODE: coverage
        run: |
          vendor/bin/phpunit --coverage-clover=coverage.xml
          cat ./coverage.xml

      - name: Show coverage.xml
        run: cat ./coverage.xml

      - name: Upload coverage.xml to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
